import type { LearningUnit } from '../types';
import type { DisciplineId } from '../types';

export const learningCatalog: LearningUnit[] = [
  {
    id: 'doomsday:weekday-numbering',
    discipline: 'doomsday',
    title: 'Ugedagenes tal',
    stage: 'teaching',
    estimatedSeconds: 60,
    isNew: true,
  },
  {
    id: 'doomsday:century-anchors',
    discipline: 'doomsday',
    title: 'Århundredernes ankre',
    stage: 'teaching',
    estimatedSeconds: 75,
    isNew: true,
  },
  {
    id: 'doomsday:year-calculation',
    discipline: 'doomsday',
    title: 'Årets dommedag',
    stage: 'teaching',
    estimatedSeconds: 90,
    isNew: true,
  },
  {
    id: 'doomsday:month-anchors',
    discipline: 'doomsday',
    title: 'Månedernes huskedatoer',
    stage: 'teaching',
    estimatedSeconds: 75,
    isNew: true,
  },
  {
    id: 'doomsday:leap-years',
    discipline: 'doomsday',
    title: 'Skudår',
    stage: 'teaching',
    estimatedSeconds: 60,
    isNew: true,
  },
  {
    id: 'doomsday:complete-date',
    discipline: 'doomsday',
    title: 'Hele datoen',
    stage: 'teaching',
    estimatedSeconds: 120,
    isNew: true,
  },
  {
    id: 'cards:suit-values',
    discipline: 'cards',
    title: 'Osterlind BCS: kulørtal',
    stage: 'teaching',
    estimatedSeconds: 40,
    isNew: true,
  },
  {
    id: 'cards:rank-reduction',
    discipline: 'cards',
    title: 'Osterlind BCS: ny kortværdi',
    stage: 'teaching',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'cards:suit-relationship',
    discipline: 'cards',
    title: 'Osterlind BCS: ny kulør',
    stage: 'teaching',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'cards:bcs-next',
    discipline: 'cards',
    title: 'Osterlind BCS: næste kort',
    stage: 'assisted',
    estimatedSeconds: 55,
    isNew: true,
  },
  {
    id: 'cards:bcs-previous',
    discipline: 'cards',
    title: 'Osterlind BCS: forrige kort',
    stage: 'assisted',
    estimatedSeconds: 55,
    isNew: true,
  },
  {
    id: 'cards:bcs-forward:2',
    discipline: 'cards',
    title: 'Osterlind BCS: flere kort frem',
    stage: 'assisted',
    estimatedSeconds: 70,
    isNew: true,
  },
  {
    id: 'cards:card-to-position:1S',
    discipline: 'cards',
    title: 'MBCS: es spar til position',
    stage: 'teaching',
    estimatedSeconds: 45,
    isNew: true,
  },
  {
    id: 'cards:position-to-card:1',
    discipline: 'cards',
    title: 'MBCS: position 1 til kort',
    stage: 'teaching',
    estimatedSeconds: 45,
    isNew: true,
  },
  {
    id: 'cards:cyclic-offsets',
    discipline: 'cards',
    title: 'MBCS: afstande i stakken',
    stage: 'assisted',
    estimatedSeconds: 60,
    isNew: true,
  },
  {
    id: 'cards:cuts-and-targets:follow-cut',
    discipline: 'cards',
    title: 'MBCS: cuts og målpositioner',
    stage: 'assisted',
    estimatedSeconds: 70,
    isNew: true,
  },
  {
    id: 'pi:prefix-diagnostic',
    discipline: 'pi',
    title: 'Pi: find dit sikre punkt',
    stage: 'teaching',
    estimatedSeconds: 90,
    isNew: true,
  },
  {
    id: 'pi:transition:5-6',
    discipline: 'pi',
    title: 'Pi: styrk de kendte cifre',
    stage: 'assisted',
    estimatedSeconds: 45,
    isNew: true,
  },
  {
    id: 'pi:bridge:4-8',
    discipline: 'pi',
    title: 'Pi: kryds en kendt overgang',
    stage: 'assisted',
    estimatedSeconds: 45,
    isNew: true,
  },
  {
    id: 'roux:first-block-intro',
    discipline: 'roux',
    title: 'Første blok',
    stage: 'teaching',
    estimatedSeconds: 90,
    isNew: true,
  },
  {
    id: 'roux:cube-orientation',
    discipline: 'roux',
    title: 'Terningens orientering',
    stage: 'assisted',
    estimatedSeconds: 60,
    isNew: true,
  },
  {
    id: 'roux:first-block-live',
    discipline: 'roux',
    title: 'First Block med den fysiske cube',
    stage: 'unassisted',
    estimatedSeconds: 180,
    isNew: true,
  },
  {
    id: 'roux:second-block-intro',
    discipline: 'roux',
    title: 'Anden blok',
    stage: 'teaching',
    estimatedSeconds: 120,
    isNew: true,
  },
  {
    id: 'roux:second-block-live',
    discipline: 'roux',
    title: 'Second Block med den fysiske cube',
    stage: 'unassisted',
    estimatedSeconds: 240,
    isNew: true,
  },
  {
    id: 'roux:cmll-intro',
    discipline: 'roux',
    title: 'CMLL i to kig',
    stage: 'teaching',
    estimatedSeconds: 180,
    isNew: true,
  },
  {
    id: 'roux:cmll-live',
    discipline: 'roux',
    title: 'CMLL med den fysiske cube',
    stage: 'unassisted',
    estimatedSeconds: 300,
    isNew: true,
  },
  {
    id: 'roux:lse-intro',
    discipline: 'roux',
    title: 'LSE i tre delmål',
    stage: 'teaching',
    estimatedSeconds: 210,
    isNew: true,
  },
  {
    id: 'roux:lse-live',
    discipline: 'roux',
    title: 'LSE med den fysiske cube',
    stage: 'unassisted',
    estimatedSeconds: 420,
    isNew: true,
  },
  {
    id: 'music-ear:interval:3:ascending',
    discipline: 'music-ear',
    title: 'Lille terts melodisk opad',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:4:ascending',
    discipline: 'music-ear',
    title: 'Stor terts melodisk opad',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:5:ascending',
    discipline: 'music-ear',
    title: 'Ren kvart melodisk opad',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:7:ascending',
    discipline: 'music-ear',
    title: 'Ren kvint melodisk opad',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:3:descending',
    discipline: 'music-ear',
    title: 'Lille terts melodisk nedad',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:4:descending',
    discipline: 'music-ear',
    title: 'Stor terts melodisk nedad',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:5:descending',
    discipline: 'music-ear',
    title: 'Ren kvart melodisk nedad',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:7:descending',
    discipline: 'music-ear',
    title: 'Ren kvint melodisk nedad',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:3:harmonic',
    discipline: 'music-ear',
    title: 'Lille terts harmonisk',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:4:harmonic',
    discipline: 'music-ear',
    title: 'Stor terts harmonisk',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:5:harmonic',
    discipline: 'music-ear',
    title: 'Ren kvart harmonisk',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:interval:7:harmonic',
    discipline: 'music-ear',
    title: 'Ren kvint harmonisk',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
  {
    id: 'music-ear:instrument-geography',
    discipline: 'music-ear',
    title: 'Find tonen',
    stage: 'assisted',
    estimatedSeconds: 50,
    isNew: true,
  },
];

export function disciplineForLearningUnitId(id: string): DisciplineId | null {
  const prefix = id.split(':')[0];
  if (prefix === 'doomsday' || prefix === 'roux' || prefix === 'cards' || prefix === 'pi')
    return prefix;
  if (prefix === 'music-ear') return 'music-ear';
  return null;
}
